kind: Probe
apiVersion: monitoring.coreos.com/v1
metadata:
  name: probe
  namespace: monitoring
spec:
  jobName: probe
  interval: 60s
  module: http_2xx
  prober:
    url: blackbox-exporter.monitoring.svc.cluster.local:19115
  targets:
    staticConfig:
      static:
      - http://example.com
      - https://example.com
