apiVersion: v1
kind: Secret
metadata:
  name: thanos-objectstorage 
  namespace: monitoring
data:
  objectstorage.yaml: ICAgIHR5cGU6IFMzCiAgICBjb25maWc6CiAgICAgICAgYnVja2V0OiAidGhhbm9zIgogICAgICAgIGVuZHBvaW50OiAibWluaW8uZGVmYXVsdC5zdmMuY2x1c3Rlci5sb2NhbDo5MDAwICIKICAgICAgICBpbnNlY3VyZTogdHJ1ZQogICAgICAgIGFjY2Vzc19rZXk6ICJtaW5pbyIKICAgICAgICBzZWNyZXRfa2V5OiAibWluaW8xMjMi
type: Opaque    
